### DISCUSSION TITLE
Best way to approach orchestration platform detection

### DISCUSSION THREAD

**Discussion by pmalek** [Kong/kubernetes-telemetry#11] [Ideas]
In order to fulfil the requirements of https://github.com/Kong/kubernetes-telemetry/blob/f230f4ad2b6078155bd359d626a7a39d36e200f2/keps/0001-telemetry.md#catalog, a way to detect the orchestration platform has to be implemented.

One of the initial ideas would be to look at the cluster nodes' labels and/or annotations and deduce the platform form that.

So for example, given that node in GKE have annotations and labels like these:

```yaml
    annotations:
      container.googleapis.com/instance_id: "1319088324951525016"
      csi.volume.kubernetes.io/nodeid: '{"pd.csi.storage.gke.io":"projects/k8s-team-playground/zones/europe-north1-a/instances/gke-cluster-default-pool-e7d79239-x65w"}'
      node.alpha.kubernetes.io/ttl: "0"
      node.gke.io/last-applied-node-labels: cloud.google.com/gke-boot-disk=pd-balanced,cloud.google.com/gke-container-runtime=containerd,cloud.google.com/gke-cpu-scaling-level=2,cloud.google.com/gke-max-pods-per-node=110,cloud.google.com/gke-nodepool=default-pool,cloud.google.com/gke-os-distribution=cos,cloud.google.com/gke-spot=true,cloud.google.com/machine-family=e2,cloud.google.com/private-node=false
      node.gke.io/last-applied-node-taints: ""
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2022-06-23T14:31:59Z"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: e2-medium
      beta.kubernetes.io/os: linux
      cloud.google.com/gke-boot-disk: pd-balanced
      cloud.google.com/gke-container-runtime: containerd
      cloud.google.com/gke-cpu-scaling-level: "2"
      cloud.google.com/gke-max-pods-per-node: "110"
      cloud.google.com/gke-nodepool: default-pool
      cloud.google.com/gke-os-distribution: cos
      cloud.google.com/gke-spot: "true"
      cloud.google.com/machine-family: e2
      cloud.google.com/private-node: "false"
      failure-domain.beta.kubernetes.io/region: europe-north1
      failure-domain.beta.kubernetes.io/zone: europe-north1-a
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: gke-cluster-default-pool-e7d79239-x65w
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: e2-medium
      topology.gke.io/zone: europe-north1-a
      topology.kubernetes.io/region: europe-north1
      topology.kubernetes.io/zone: europe-north1-a
```

We could in such a case detect GKE based on the existence of:

* `container.googleapis.com/instance_id` annotation
* `topology.gke.io/zone` label

and perhaps some others **OR** we could base our logic on the version that we get from `k8s.io/client-go/kubernetes.(discovery.ServerVersionInterface).ServerVersion()` call, e.g. `v1.24.0-gke.1801`. Not sure how reliable is that though. Given that other cloud providers also add something similar in the version string, maybe that's the way to go?
